### ISSUE TITLE
Runfo edits issues when there is no change

### ISSUE THREAD

**Issue by ericstj** [jaredpar/runfo#165]
I noticed that Runfo will continuously edit live issues, filling up the issue edit history and making it very difficult to go back and see trends.  @viktorhofer also mentioned that this is unbounded growth the GitHub's issue storage as well.

**Comment by ViktorHofer** [comment]
cc @jaredpar

**Comment by jaredpar** [comment]
>  @ViktorHofer also mentioned that this is unbounded growth the GitHub's issue storage as well.

How do you view this? Never seen issue storage displayed anywhere before. 

> I noticed that Runfo will continuously edit live issues, filling up the issue edit history and making it very difficult to go back and see trends

Let me see how easy that is to fix.

**Comment by jaredpar** [comment]
Verified the fix is working 

> 2022-08-05T02:37:14.550 [Information] Executing 'issues-update-manual' (Reason='This function was programmatically called via the host APIs.', Id=b7397ac2-d2ce-4372-adff-ac95803705d6)
2022-08-05T02:37:17.122 [Information] Updating 415
2022-08-05T02:37:19.475 [Information] **No change in body, skipping update**
2022-08-05T02:37:19.476 [Information] Updated https://github.com/dotnet/runtime/issues/73343
2022-08-05T02:37:19.486 [Information] Executed 'issues-update-manual' (Succeeded, Id=b7397ac2-d2ce-4372-adff-ac95803705d6, Duration=5558ms)

**Comment by ViktorHofer** [comment]
> How do you view this? Never seen issue storage displayed anywhere before.

AFAIK there's no way to access that data but these unnecessary updates might cause storage issues eventually. We saw something similar in https://github.com/dotnet/runtime/issues/68440 which we fixed by cleaning up the old workflow runs.
